#!/bin/bash -x 
# script to create executalbe file for command
# following pluralsight tutorial

commandname=$1
bindir="${HOME}/bin-test"
scriptdir="${HOME}/script"
filename="${scriptdir}/${commandname}"
symlinkfilename="${bindir}/${commandname}"

# check if script name provided
if [[ ! $commandname ]]; then
    echo "Script name not provided"
    exit 1
fi

# check if command with same name exist
if type "${commandname}" > /dev/null 2>&1; then #to discard type output and error message
    echo "Command with name ${commandname} exist"
    exit 1
fi

# check if bin directory  exist else create
if [[ ! -d $bindir ]]; then
    if mkdir "${bindir}"; then
        echo "created ${bindir}"
    else
        echo "error creating ${bindir}"
        exit 1
    fi
fi

# create file 
touch "${filename}"

# create symlink of script file in bin
ln -s "${filename}" "${symlinkfilename}"

# add permission
chmod u+x "${filename}"

# add bin bash to the file
echo "#!/bin/bash" >> "${filename}"

# add how file was called 
echo "echo \$0" >> "${filename}"

# if editor is not designed it will execute the first line of filename and hence if else added
if [[ $EDITOR ]]; then
    $EDITOR "$filename"
else
    echo "\$EDITOR not set. set using export EDITOR=<value>"
fi
exit 0
