#!/bin/bash

# takes notes in home director notes folder
# Author: Sumant Dey

#get the date
date=$(date)

#get the topic
topic=$1

#file to write to
filename="${HOME}/notes/${topic}notes.txt"

read -p "Your note: " note

if [[ $note ]]; then
    echo "${date} : ${note}" >> "$filename"
    echo "Note ${note} saved to ${filename}"
else
    echo "no input: note wasn't saved" 1>&2 #redirecting output to err for this cmd as this is error
    # another way of doing it > /dev/stderr
fi
